export const skillsSet = {
    HTML: ['Semantics', 'Accessability'],
    CSS: [
        'RWD',
        'Flex',
        'Grid',
        'Sass modules',
        'Tailwind',
        'Styled Components',
    ],
    JS: ['ES6+ features', 'async/await', 'Promises', 'Typescript'],
    React: [
        'React Router',
        'Redux-Saga',
        'Redux Toolkit',
        'React-tooltip',
        'React-scroll',
        'React-modal',
        'React-select',
        'React-toastify',
        'React-google-maps',
        'React-hook-form',
        'React-cookie',
    ],
    Next: [
        'Routing',
        'Server-side Rendering',
        'Static Site Generation',
        'Next-auth',
        'Next-translate',
    ],
    Others: [
        'NPM',
        'PNPM',
        'GIT',
        'Storybook',
        'Dayjs',
        'Husky',
        'Cypress',
        'TanStack Query',
        'Lodash',
        'Yup',
    ],
};
